### ISSUE TITLE
RATDecoders don't have Malware Names

### ISSUE THREAD

**Issue by cccs-kevin** [CybercentreCanada/assemblyline-service-configextractor#3]
Based on the current logic, malware names for RATDecoders are always "" because files in RATDecoders/malwareconfigs/decoders are never entered into the yara_parser.yml and therefore never entered into the self.file_parsers list. This results in the attribution.implant tag being set to an empty string if a RAT file is submitted, which could cause issues with the way that the result is parsed, plus it's currently a tag that doesn't provide any information. 

Example hash:
ea333f245dd40d74cbfef974d674df4db5bf6893dd22f3e4388add96bb5435af

**Comment by cccs-aa** [comment]
This commit sets the implant tag. This is the simplest way to fix it. Adding it to file_parsers would require a lot more restructuring of code due to the differences between RATDecoders and MWCP parsers. What do you think.
https://github.com/CybercentreCanada/assemblyline-service-configextractor/commit/88de1442e8dcb41f77021b863d7d5628c0890786#diff-1f6a35044908431c90a65cff961c00967a2d43bd9c9e06f8ac6daacb8918fc01R137

**Comment by cccs-kevin** [comment]
https://github.com/CybercentreCanada/assemblyline-service-configextractor/commit/1c0ccd45780db6c2df5bec9b1129924ebc45d462
